# Generated by Django 4.2.6 on 2023-11-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
